### ISSUE TITLE
feature - Tags hinzufügen und löschen UI

### ISSUE THREAD

**Issue by sorrowcode** [sorrowcode/taesch-#41]
Als Nutzer möchte ich Tags dynamisch hinzufügen oder löschen, damit ich mir meinen Einkaufszettel individuell gestalten kann.
Hier soll mittels grafischer Oberfläche ein Tag zu einem Einkaufselement hinzugefügt oder gelöscht werden.

**Comment by jonycoo** [comment]
habe es jetzt so, das bei anlagen eines Einkaufselements tags hinzugefügt und gelöscht werden können.
Für die genaue darstellung von Tags ist #14

**Comment by robinhefner** [comment]
Wenn du noch nen Pull request erstellst kann ich gleich damit anfangen :D

**Comment by jonycoo** [comment]
@D4rkm4n215 muss noch den merge conflikt voher lösen, hosse das ich das heut aben noch hin bekomme.
