### ISSUE TITLE
feature - Tags hinzufügen und löschen

### ISSUE THREAD

**Issue by sorrowcode** [sorrowcode/taesch-#42]
Als Nutzer möchte ich, nach dem ich die Tags erstellt habe, dass die Tags gespeichert werden. Beim Löschen sollen diese auch entfernt werden.
Hier soll die SQL-Schnittstelle um die Funktionalität Erstellen und Löschen erweitert werden.

**Comment by jonycoo** [comment]
6 files changed  with 155 additions and 20 deletions.
latest commit was d8720a529c12064385e2e11a90d4a25623c315e1

Änderung im daten modell des Shopping Items und Priorisirungs Algoritmus haben diese Änderungen überflüssig gemacht. gemacht.
