### ISSUE TITLE
feature - Info bei keinem Internet oder GPS

### ISSUE THREAD

**Issue by sorrowcode** [sorrowcode/taesch-#50]
Als Nutzer möchte ich wissen, wenn ich die App nutze, ob meine Einstellungen das Nutzen der App zulassen (Internet & GPS), damit ich die Funktionen der App benutzen kann.
Hierbei soll die Nutzereinstellung des Smartphones überprüft werden. Sollte eine der Einstellungen oder beide deaktiviert werden, soll mittels Pop-Ups darauf hingewiesen werden und die Möglichkeit geboten werden, diese Einstellung vorzunehmen.

**Comment by maximilianley** [comment]
diese Einstellung ist jetzt zum Teil implementiert (für den GPS Service). Im Pull Request 59 ist das Issue "Autorisierung - GPS" verlinkt. Im Settings-Screen kann man dort einstellen ob GPS erlaubt sein soll, und sich Hilfe holen über einen Hilfebutton (Pop Up)

Sorry hab nicht gemerkt dass es ein Issue dafür gab. Habs eig nur gemacht weil das auch mit den Permissions zu tun hat
