### ISSUE TITLE
bug - nearshopsScreen search läd items nicht 

### ISSUE THREAD

**Issue by RedConcrete** [sorrowcode/taesch-#59]
Searchbutton muss mehr mal gedrückt werden um die liste zu laden

**Comment by RedConcrete** [comment]
NEEEED THIS BUG FIXED NOWWWWWWWW

**Comment by sorrowcode** [comment]
@maximilianley du bist da schon dran gell?

**Comment by maximilianley** [comment]
hi, ja bin dran, bzw. es geht schon. Muss noch den Pullrequest machen
